services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: VERTEX-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    restart: unless-stopped